name = "PhysicsTools"
uuid = "aacfb283-0df6-49c4-85a4-270b72c3b0a9"
authors = ["Christian Haack"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
